
server:
  port: 10006
spring:
  application:
    name: dispensary
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 765681806@qq.com
    password: qfvssbcaknasbcij
  thymeleaf:
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
multipart:
  maxFileSize: 500Mb
  maxRequestSize: 500Mb



