server:
  port: 10031
eureka:
  client:
    service-url:
     defaultZone: http://10.12.159.32:8766/eureka
spring:
  application:
    name: comment-server-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/traval?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapping/*xml
  type-aliases-package: com.qf.j1902.pojo